server:
  port: 20000
  ip: 0.0.0.0
  max-threads: 300
  max-connections: 600
  name: entry_01

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE

orderDomain:
  maxAllowedTimeConsume: 500

spring:
  dataSource:
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    minIdle: 5
    validationQuery: select 1
    public:
      url: jdbc:mysql://localhost:3307/order_public
    ind_0:
      url: jdbc:mysql://localhost:3307/order_index_0
    ind_1:
      url: jdbc:mysql://localhost:3307/order_index_1
    ind_2:
      url: jdbc:mysql://localhost:3307/order_index_2
    ind_3:
      url: jdbc:mysql://localhost:3307/order_index_3

mq:
  rocketmq:
    group: demo
    nameSvr: localhost:9876
    orderTopic:
      topic: orderTopic
    consumerGroup: demo-consumer

