server:
  port: 20000
  ip: 0.0.0.0
  max-threads: 300
  max-connections: 600

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE